# configs/models/stfpm.yaml

model:
  name: efficientad
  module: defectvad.models.efficientad.torch_model
  class: EfficientAdModel

trainer:
  name: efficientad
  module: defectvad.models.efficientad.trainer
  class: EfficientAdTrainer

  params:
    teacher_out_channels: 384
    model_size: small
    padding: false
    pad_maps: true

  max_epochs: 50
  validate: true

dataset:
  normalize: false

dataloader:
  train:
    batch_size: 1
