# configs/datasets/mvtec.yaml

dataset:
  name: mvtec
  module: defectvad.data.datasets
  class: MVTecDataset

  # dataset transform defaults
  img_size: 256
  crop_size: null
  normalize: true
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

dataloader:
  # train dataloader defaults  
  train:
    batch_size: 16

    params:
      shuffle: true
      drop_last: true
      num_workers: 4
      pin_memory: true

  # test dataloader defaults  
  test:
    batch_size: 16
    
    params:
      shuffle: false
      drop_last: false
      num_workers: 4
      pin_memory: true
