# configs/models/stfpm.yaml

model:
  name: stfpm
  module: defectvad.models.stfpm.torch_model
  class: STFPMModel

trainer:
  name: stfpm
  module: defectvad.models.stfpm.trainer
  class: STFPMTrainer

  params:
    backbone: resnet50
    layers: [layer1, layer2, layer3]

  max_epochs: 50
  validate: true

# dataset:
#   normalize: false

# dataloader:
#   train:
#     batch_size: 32
